name: Base64 Tester

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  decode:
    runs-on: ubuntu-latest
    steps:
      - name: Decode some value
        id: decode_upload_some_value
        uses: timheuer/base64-to-file@v1
        with:
          fileName: some_value.txt
          encodedString: ${{ secrets.SOME_SECRET }}