name: "ENV vars"

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: envvars
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Show workspace
      run: echo ${{ github.workspace }}
      
    - name: Set date env
      run: |
        Write-Host "CURRENT_DATE=$(Get-Date -format "yyyyMMdd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: powershell

    - name: Vars
      run: |
        echo "Run ID: ${{ github.run_id }}"
        echo "Run Num: ${{ github.run_number }}"
        echo $CURRENT_DATE

    - name: Var echo 2
      run: |
        echo $env:$CURRENT_DATE
      shell: powershell
