name: "setup-msbuild"

on:
  workflow_dispatch:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: setup-msbuild
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: setup msbuild
      uses: microsoft/setup-msbuild@v1.3

    - name: echo msbuild
      run: |
        msbuild -version

    - name: restore
      run: dotnet restore
      
    - name: build
      run: |
        msbuild runner-testing.csproj
