name: "windows-testing"

on:
  workflow_dispatch:
    branches:
      - main
      
jobs:
  build:
    name: run stuff
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup msbuild
      uses: microsoft/setup-msbuild@v2

    - name: npm install
      run: |
        npm install

    - name: node test
      if: always()
      run: |
        node run
